apiVersion: v1
kind: Pod
metadata:
  name: with-tol
spec:
  tolerations:
  - key: test
    operator: Equal
    value: "true"
    effect: NoSchedule     # matches the taint exactly
  containers:
  - name: app
    image: nginx